---
abstract: 'Merges arbitrarily deep hashes into a single hash'
author:
  - 'Michael K. Neylon <mneylon-pm@masemware.com>'
  - 'Daniel Muey <dmuey@cpan.org>'
  - 'Jens Rehsack <rehsack@cpan.org>'
  - 'Stefan Hermes <hermes@cpan.org>'
build_requires:
  Test::More: '0.9'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Hash-Merge
no_index:
  directory:
    - t
    - inc
requires:
  Clone::Choose: '0.008'
  Scalar::Util: '0'
  perl: v5.8.1
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Hash-Merge
  homepage: https://metacpan.org/release/Hash-Merge
  license: http://dev.perl.org/licenses/
  repository: https://github.com/perl5-utils/Hash-Merge.git
version: '0.302'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
